name: lab-vistas

services:
  mariadb:
    image: mariadb:11
    container_name: lab_vistas_mariadb
    env_file:
      - .env
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE:-sales_system_db}
      MARIADB_USER: ${APP_USER:-lab_user}
      MARIADB_PASSWORD: ${APP_USER_PASSWORD:-lab_pass}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-rootpass}
    ports:
      - "${HOST_PORT:-3307}:3306"
    volumes:
      - lab_vistas_mariadata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-uroot", "-p${MARIADB_ROOT_PASSWORD:-rootpass}"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  lab_vistas_mariadata:
